# Generated by Django 4.2.11 on 2024-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to=None)),
                ('uploaded_time', models.DateTimeField(verbose_name='Upload date')),
                ('price', models.IntegerField(max_length=4, verbose_name='Price Field')),
                ('description', models.CharField(max_length=120, verbose_name='product Name')),
                ('owner', models.CharField(max_length=120, verbose_name='Owner Name')),
                ('availability', models.BigIntegerField(max_length=120, verbose_name='disponibilità')),
            ],
        ),
    ]
